Add default makefile generator to configure
Saves you writing it yourself when you make a new project with this
configure script. Probably lost more time doing this than it'll save

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -124,4 +124,30 @@ done
 	done
 } >config.mk
 
+if ! [ -e Makefile ]; then
+	printf 'Makefile not found; create one? [Y/n] '
+	read -r ans
+	case "$ans" in
+		y*|Y*|'')
+			cat >Makefile <<'EOF'
+.POSIX:
+include config.mk
+
+.PHONY: clean
+clean:
+	rm -rf ${BUILDDIR}
+
+${BUILDDIR}/bin/%: ${BUILDDIR}/obj/%.o
+	@mkdir -p $$(dirname $@)
+	${CC} -o $@ $^ ${LDFLAGS}
+
+${BUILDDIR}/obj/%.o: %.c config.mk
+	@mkdir -p $$(dirname $@)
+	${CC} ${CFLAGS} -c -o $@ $<
+EOF
+			;;
+		*) ;;
+	esac
+fi
+
 true
