Add conditional static linking to configure script
glibc is bad. Especially at static linking. So we detect it by trying to
include a glibc-specific header (__GLIBC__ macro is unreliable, uClibc
defines it and probably others), and disable static linking if it succeeds

musl-clang and musl-gcc are used in preference to normal compilers, as
this will allow us to statically link to musl even on glibc-native systems

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,9 +9,18 @@ conf() {
 		TARGETS="$TARGETS $BUILDDIR/bin/${f%.c}"
 	done
 
-	CC="$(detect clang gcc cc)" || error 'Could not find C compiler'
+	CC="$(detect musl-clang musl-gcc clang gcc cc)" || error 'Could not find C compiler'
 	CFLAGS='-std=c99 -Wall -pedantic -D_XOPEN_SOURCE=700'
 	LDFLAGS=
+
+	if [ -z "${CC##musl-*}" ]; then
+		CFLAGS="$CFLAGS -Wno-unused-command-line-argument"
+		LDFLAGS="$LDFLAGS -Wno-unused-command-line-argument"
+	fi
+
+	if [ -z "${CC##musl-*}" ] || ! libc_is_gnu; then
+		LDFLAGS="$LDFLAGS -static"
+	fi
 }
 
 develconf() {
@@ -39,12 +48,15 @@ detect() {
 	false
 }
 
+libc_is_gnu() {
+	# Check if the compiler's libc is glibc
+	echo '#include <gnu/libc-version.h>' |
+	"$CC" $CFLAGS -E - >/dev/null 2>&1
+}
+
 deps() {
 	# Find the dependencies of a C file
-	cpp="$(detect cpp "$CC")"
-	[ -z "$cpp" ] && error 'Could not find C preprocessor'
-
-	"$cpp" $CFLAGS -E "$1" |
+	"$CC" $CFLAGS -E "$1" |
 	grep '^[ \t]*#[ \t]*\(line\|[ \t]\)[0-9]\+[ \t]\+"[^<>"]\+"' |
 	sed 's/^[^"]*"\([^<>"]\+\)".*$/\1/' |
 	sort -ur |
